version: "3.7"

services:
  test:
    build: .
    image: izolenta
    command: service postgresql start && rake test
    volumes:
      - '.:/app'

  test3:
    build:
      context: .
      dockerfile: ruby3.Dockerfile
    image: izolenta3
    command: service postgresql start && rake test
    volumes:
      - '.:/app'
